batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Models/04_sentence_recognition/202309022119
train_epochs: 10
train_workers: 20
vocab: yk-H5hBN'CUS#fbq,0u*:4MF(KJZ2WnxEDLave?Ot/sr3AG87;Y Xl+Tp9&Qz)I6Vo1.c!PR"wjimgd
width: 1408
